package pt.isel.reversi.cli

import pt.isel.reversi.utils.CLI_CONFIG_FILE
import pt.isel.reversi.utils.ConfigLoader

val CLI_CONFIG: CliConfig = ConfigLoader(CLI_CONFIG_FILE) { CliConfig(it) }.loadConfig()

val WELCOME_MESSAGE = CLI_CONFIG.WELCOME_MESSAGE
val PROMPT = CLI_CONFIG.PROMPT
val PROMPT_COLOR = CLI_CONFIG.PROMPT_COLOR
val TEXT_COLOR = CLI_CONFIG.TEXT_COLOR
val ERROR_COLOR = CLI_CONFIG.ERROR_COLOR
val WARNING_COLOR = CLI_CONFIG.WARNING_COLOR
val INFO_COLOR = CLI_CONFIG.INFO_COLOR
val HELP_USAGE_COLOR = CLI_CONFIG.HELP_USAGE_COLOR
val HELP_ALIAS_COLOR = CLI_CONFIG.HELP_ALIAS_COLOR
val HELP_DESC_COLOR = CLI_CONFIG.HELP_DESC_COLOR
